### ISSUE TITLE
Document organization audits API endpoint

### ISSUE THREAD

**Issue by kimmoahokas** [flowdock/api-docs#60]
Apparently there is endpoint `/organizations/:organization/audits/users` endpoint that lists at least when user has used that organization last time. Please document this endpoint (and other things that can possibly be found under `/organizations/:organization/audits/`.

**Comment by Mumakil** [comment]
We're not going to do that at least for the current endpoint. These are still experimental and undocumented for that reason, and all audit data availability outside of Flowdock Enterprise is still under consideration.
